/**
 * writeConfig — serialise a Config object to YAML and write it to disk.
 *
 * No external yaml package required. The Config shape is flat enough that
 * a purpose-built emitter is both simpler and faster to load than a full
 * YAML library. Add the `yaml` package when Config grows nested lists.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { Config } from './config.js';

/** Emit a scalar value as a YAML-safe string (no quoting for safe values). */
function yamlScalar(v: unknown): string {
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') {
    // Quote strings that contain special YAML chars or are booleans/numbers.
    if (
      v === '' ||
      /[:#{}\[\],&*?|<>=!%@`]/.test(v) ||
      /^(true|false|null|~)$/i.test(v) ||
      /^\d/.test(v)
    ) {
      return `'${v.replace(/'/g, "''")}'`;
    }
    return v;
  }
  return String(v);
}

/** Emit one YAML line with optional indent. */
function line(indent: number, key: string, value?: unknown): string {
  const pad = '  '.repeat(indent);
  if (value === undefined) return `${pad}${key}:`;
  return `${pad}${key}: ${yamlScalar(value)}`;
}

/**
 * Serialise Config to a YAML string.
 *
 * The emitted YAML is intentionally hand-readable and round-trippable by
 * `js-yaml` / `yaml` if the user installs one later.
 */
export function configToYaml(cfg: Config): string {
  const lines: string[] = [
    '# AstraMemory Local — config.yaml',
    '# Generated by `astra-memory init`. Edit manually or re-run init.',
    '',
    line(0, 'port', cfg.port),
    line(0, 'dataDir', cfg.dataDir),
    '',
    line(0, 'llm'),
    line(1, 'compaction'),
    line(2, 'provider', cfg.llm.compaction.provider),
    line(2, 'model', cfg.llm.compaction.model),
    line(1, 'extraction'),
    line(2, 'provider', cfg.llm.extraction.provider),
    line(2, 'model', cfg.llm.extraction.model),
    '',
    line(0, 'embedding'),
    line(1, 'provider', cfg.embedding.provider),
    line(1, 'model', cfg.embedding.model),
    line(1, 'dim', cfg.embedding.dim),
    '',
    line(0, 'vector'),
    line(1, 'store', cfg.vector.store),
    '',
    line(0, 'budget'),
    line(1, 'daily_usd', cfg.budget.daily_usd),
    '',
    line(0, 'ollama'),
    line(1, 'baseUrl', cfg.ollama.baseUrl),
    '',
    line(0, 'azure'),
    line(1, 'apiVersion', cfg.azure.apiVersion),
    ...(cfg.azure.endpoint ? [line(1, 'endpoint', cfg.azure.endpoint)] : []),
    ...(cfg.azure.deployment ? [line(1, 'deployment', cfg.azure.deployment)] : []),
    '',
    line(0, 'search'),
    line(1, 'alpha', cfg.search.alpha),
    line(1, 'beta', cfg.search.beta),
    line(1, 'gamma', cfg.search.gamma),
    line(1, 'delta', cfg.search.delta),
    '',
  ];
  return lines.join('\n');
}

/**
 * Write config.yaml to `path`, creating parent directories as needed.
 */
export function writeConfig(cfg: Config, path: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, configToYaml(cfg), 'utf8');
}
